apiVersion: v1
kind: Service
metadata:
  name: {{ include "apt.fullname" . }}-{{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    apt.kubernetes.io/tier: {{ include "apt.name" . }}-{{ .Values.frontend.name }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.container.targetPort }}
