#########################################################################################################################
#                                                                                                                       #
#  Run override compose with e2e tests:                                                                                 #
#  docker compose -f docker-compose.yml -f docker-compose.e2e.yml up --exit-code-from cypress                           #
#                                                                                                                       #
#  NOTE:                                                                                                                #
#  If you build and run container without this compose, you need to pass variable:                                      #
#  docker build --no-cache -f .\e2e\cypress.Dockerfile -t cypress-test .\e2e\                                           #
#  docker run --network air-pollution-tracker_apt-network -e CYPRESS_FRONTEND_URL=http://frontend:3000                  #
#  -e API_BASE_URL=http://backend:9000 cypress-test                                                                     #
#                                                                                                                       #
#  BE AWARE:                                                                                                            #
#  When running tests, you need to send reqests to direct container, without proxing reqests via localhost, which       #
#  is used in app itself                                                                                                #
#                                                                                                                       #
#  Copy screens:                                                                                                        #                   
#  docker cp <container_id>:/app/cypress/screenshots .\e2e\screenshots\                                                 #
#                                                                                                                       #
#########################################################################################################################

services:
  cypress:
    build:
      context: ./e2e
      dockerfile: cypress.Dockerfile
    depends_on:
      - frontend
      - backend
      - calc_module
      - rabbitmq
    environment:
      - CYPRESS_FRONTEND_URL=http://frontend:3000
      - API_BASE_URL=http://backend:9000
    networks:
      - apt-network

networks:
  apt-network:
    name: air-pollution-tracker_apt-network