apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apt-developer-rolebinding
  namespace: default
subjects:
- kind: User
  name: apt-developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: apt-developer-role
  apiGroup: rbac.authorization.k8s.io