apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apt.name" . }}-{{ .Values.calc_module.name }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  replicas: {{ .Values.calc_module.replicaCount }}
  selector:
    matchLabels:
      apt.kubernetes.io/tier: {{ include "apt.name" . }}-{{ .Values.calc_module.name }}
      apt.kubernetes.io/version: {{ include "apt.version" . }}
  template:
    metadata:
      labels:
        apt.kubernetes.io/tier: {{ include "apt.name" . }}-{{ .Values.calc_module.name }}
        apt.kubernetes.io/version: {{ include "apt.version" . }}
    spec:
      nodeSelector:
        deployment: {{ .Values.eks.cluster.nodeGroup }}
      containers:
        - name: {{ .Values.calc_module.name }}
          image: "{{ .Values.calc_module.image.repository }}:{{ .Values.calc_module.image.tag }}"
          imagePullPolicy: {{ .Values.calc_module.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.calc_module.resources.requests.memory }}
              cpu: {{ .Values.calc_module.resources.requests.cpu }}
            limits:
              memory: {{ .Values.calc_module.resources.limits.memory }}
              cpu: {{ .Values.calc_module.resources.limits.cpu }}
          envFrom:
            - configMapRef:
                name: {{ include "apt.name" . }}-config
          ports:
            - containerPort: {{ .Values.calc_module.container.targetPort }}
