apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apt.fullname" . }}-config
data:
  REACT_APP_API_BASE_URL: "http://{{ .Values.ingress.host }}/api"
  ORIGIN: "http://{{ .Values.ingress.host }}" 
  PRISMA_CLI_BINARY_TARGETS: {{ .Values.backend.environment.PRISMA_CLI_BINARY_TARGETS | quote }}
  RABBITMQ_REQUEST_QUEUE: {{ .Values.backend.environment.RABBITMQ_REQUEST_QUEUE | quote }}
  RABBITMQ_URL: "amqp://{{ .Values.rabbitmq.config.RABBITMQ_DEFAULT_USER }}:{{ .Values.rabbitmq.config.RABBITMQ_DEFAULT_PASS }}@{{ include "apt.fullname" . }}-{{ .Values.rabbitmq.name }}:{{ .Values.rabbitmq.service.ports.amqp }}"

