apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apt.name" . }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.SSL_CERTIFICATE }}
  tls.key: {{ .Values.secrets.SSL_CERTIFICATE_KEY }}