apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apt.fullname" . }}-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apt.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
