name: Create ECR repository

on:
    workflow_dispatch:

env:
    AWS_REGION: ${{ vars.AWS_REGION }}
    ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

jobs:
    create-ecr:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Check if ECR repository exists
              id: check-ecr
              run: |
                set -e
                if aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} > repository_info.json; then
                    echo "ECR repository ${{ env.ECR_REPOSITORY }} already exists."
                    cat repository_info.json
                    echo "::set-output name=ECR_EXISTS::true"
                else
                    echo "ECR repository ${{ env.ECR_REPOSITORY }} does not exist."
                    echo "::set-output name=ECR_EXISTS::false"
                fi

            - name: Create ECR repository
              if: steps.check-ecr.outputs.ECR_EXISTS == 'false'
              run: |
                aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY }}
                echo "ECR repository created successfully."
